name: Flutter Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # Apne Flutter version ke hisaab se change karo

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Gradle wrapper (agar missing ho)
        run: |
          sudo apt-get install gradle -y
          cd android
          gradle wrapper
          cd ..

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
